name: Build PIPA NOKSU Devices Kernel

on:
  workflow_dispatch:
  push:
    tags: ['v*']  # 添加标签触发

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        device: [pipa]

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git curl wget bison flex zip bc cpio libssl-dev ccache python-is-python3 unzip

    - name: Setup proton-clang toolchain
      run: |
        mkdir -p $HOME/proton-clang
        cd $HOME/proton-clang
        wget https://github.com/kdrag0n/proton-clang/archive/refs/tags/20210522.zip
        unzip 20210522.zip
        cd $GITHUB_WORKSPACE

    - name: Build kernel for ${{ matrix.device }} (No KSU)
      run: |
        bash build.sh ${{ matrix.device }}

    - name: List generated files
      run: ls -la *.zip || echo "No zip files found"

    - name: Upload flashable zips for ${{ matrix.device }}
      uses: actions/upload-artifact@v4
      with:
        name: kernel-${{ matrix.device }}-noksu-${{ github.run_id }}
        path: |
          *.zip
        retention-days: 30
        if-no-files-found: error

    - name: Upload build logs (optional)
      uses: actions/upload-artifact@v4
      with:
        name: build-logs-${{ matrix.device }}-noksu
        path: |
          **/*.log
          **/*.txt
        retention-days: 7
        if-no-files-found: ignore
